### ISSUE TITLE
Compilation tensorflow version is not always works

### ISSUE THREAD

**Issue by jeugregg** [edeltech/tensorflow-lite-on-aws-lambda#2]
For the part : "Clone TensorFlow from the official GitHub repository", we need to force a version of tensorflow because sometimes latest version is not compiling well.

For my case, I want tensorflow v2.3.0, so i modified this line : 

`git clone  https://github.com/tensorflow/tensorflow.git`
by 
`git clone --branch v.2.3.0 https://github.com/tensorflow/tensorflow.git`

**Comment by jpgehrig** [comment]
Hi @jeugregg, thanks for you feedback. We have updated the example code and the [accompanying blog post](https://www.edeltech.ch/blog/2020-07-11-how-to-deploy-a-tensorflow-lite-model-on-aws-lambda/) to use Lambda Container Images. Now we can use the latest TensorFlow.
